### ISSUE TITLE
Crahs on GDPR and CCPA window.

### ISSUE THREAD

**Issue by vlad-arpa** [appodeal/appodeal-unity-plugin-upm#10]
## Step 1: Environment

 - Computer OS: Windows
 - Unity Editor Version: 2020.3.43f1
 - Appodeal Unity Plugin Version: 3.0.1 , 3.0.2
 - Bug Repro Rate: 100%
 - Device OS: Android

## Step 2: Describe the bug
When you start the game on a device with vpn enabled, when the "GDPR and CCPA" window appears or when the window has already appeared, if you minimize the game and then expand it, the game continues without a window, it works for a couple of seconds, then freezes, and after a while it issues too many bugs and the game crashes

## Step 3: How to reproduce
0. Put vpn on a European address.
1. Start the game.
2. Wait for the message.
3. Minimize the game.
4. * Click on the shortcut to launch the game on your phone.
5. Game starts window no more.
6. The game works for a couple of seconds, then freezes.
7. Wait for errors in the logcat.

* Sometimes this error is repeated if you simply expand the game again (without launching through the icon), and sometimes if you minimize the game before the window appears, but when it should now appear

## Step 4: Expected behavior
Continuing the game in stable mode.

**Comment by DmitriiFeshchenko** [comment]
Hi, @vlad-arpa! 👋 

Thanks for reporting this issue.

During project build, Unity adds this property to their activity:
`android:launchMode="singleTask"`
And so the app closes all other activities except UnityPlayerActivity when it comes to the foreground.

If you override this value with the default one for android, it will work just fine.
```
tools:replace="android:launchMode"
android:launchMode="standard"
```

Although, it may affect Unity Engine's work in many ways. Thus, I do not recommend you to do that unless you know how it works and what can be affected.

We will add a fix to the ConsentActivity onDestroy() callback in the upcoming release of Appodeal SDK. It should be 3.1.0, which is planned to be released in 2-4 weeks.

**Comment by vlad-arpa** [comment]
how soon will the update be?

**Comment by DmitriiFeshchenko** [comment]
Hi, @vlad-arpa!

We are currently conducting a beta test of v3.1.0. If all goes well, it will be released in a few weeks.

However, as I can see, the Android team has also added this fix to v3.0.2. But in order to install it, you will have to [clear the gradle cache](https://stackoverflow.com/a/47344597) first and then rebuild your project. I've just checked and wasn't able to reproduce this bug anymore.

**Comment by DmitriiFeshchenko** [comment]
> 1. Put vpn on a European address.
> 2. Start the game.
> 3. Wait for the message "window ask" - GDPR and CCPA.
> 4. Minimize the game.
> 5. Click on the shortcut to launch the game on your phone.
> 6. Game starts "window ask" no more.
> 7. The game dont load ad, and next run's game, dont show "window ask" and dont load ad

It's the correct and expected behavior up to p7.

@vlad-arpa, I've tried to reproduce this issue once again but no luck. Could you please check it on your device using [this demo .apk](https://drive.google.com/file/d/1Vox_zq3onw_Z5zm107Uz9zR5ZDi87eI-/view?usp=sharing)? If it works, then I guess that you didn't clear the gradle cache as I suggested [earlier](https://github.com/appodeal/appodeal-unity-plugin-upm/issues/10#issuecomment-1473526436). Please, let me know how it goes. If there is an issue, we will fix it as soon as possible.

**Comment by vlad-arpa** [comment]
But in your apk, when you click on the initialization button, the window with the "consent" does not come out by itself, in order for it to come out you need to press another button, in my application it is done so that when initializing the window comes out automatically, you have automatic appearance turned off.

Maybe you try to create an application for yourself where it will be just initialization and nothing more (in this case, the window appears by itself), to repeat my case with the automatic appearance of the window

**Comment by DmitriiFeshchenko** [comment]
@vlad-arpa, I assume, that you didn't enable the "testing" mode which led to consent being set as NonPersonalized. It's because of the demo app logic. Could you please give it another try (fresh install), with testing enabled?

[device-2023-03-23-090207.webm](https://user-images.githubusercontent.com/43773640/227140142-c1224f7f-9c98-4ca6-8866-da036d89487c.webm)

**Comment by vlad-arpa** [comment]
I checked your application and mine, the problem seems to have really disappeared
